# word_list = [
#     'abruptly',
#     'absurd',
#     'abyss',
#     'affix',
#     'askew',
#     'avenue',
#     'awkward',
#     'axiom',
#     'azure',
#     'bagpipes',
#     'bandwagon',
#     'banjo',
#     'bayou',
#     'beekeeper',
#     'bikini',
#     'blitz',
#     'blizzard',
#     'boggle',
#     'bookworm',
#     'boxcar',
#     'boxful',
#     'buckaroo',
#     'buffoon',
#     'buxom',
#     'buzzard',
#     'buzzing',
#     'buzzwords',
#     'caliph',
#     'cobweb',
#     'cockiness',
#     'croquet',
#     'crypt',
#     'curacao',
#     'cycle',
#     'daiquiri',
#     'dirndl',
#     'disavow',
#     'dizzying',
#     'duplex',
#     'buffalo',
#     'dwarves',
#     'embezzle',
#     'equip',
#     'espionage',
#     'euouae',
#     'exodus',
#     'faking',
#     'fishhook',
#     'fixable',
#     'fjord',
#     'flapjack',
#     'flopping',
#     'fluffiness',
#     'flyby',
#     'foxglove',
#     'frazzled',
#     'frizzled',
#     'fuchsia',
#     'funny',
#     'gabby',
#     'galaxy',
#     'galvanize',
#     'gazebo',
#     'giaour',
#     'gizmo',
#     'glowworm',
#     'glyph',
#     'gnarly',
#     'gnostic',
#     'gossip',
#     'grogginess',
#     'haiku',
#     'haphazard',
#     'hyphen',
#     'iatrogenic',
#     'icebox',
#     'injury',
#     'ivory',
#     'ivy',
#     'jackpot',
#     'jaundice',
#     'jawbreaker',
#     'jaywalk',
#     'jazziest',
#     'jazzy',
#     'jelly',
#     'jigsaw',
#     'jinx',
#     'jiujitsu',
#     'jockey',
#     'jogging',
#     'joking',
#     'jovial',
#     'joyful',
#     'juicy',
#     'jukebox',
#     'jumbo',
#     'kayak',
#     'kazoo',
#     'keyhole',
#     'khaki',
#     'kilobyte',
#     'kiosk',
#     'kitsch',
#     'kiwifruit',
#     'klutz',
#     'knapsack',
#     'larynx',
#     'lengths',
#     'lucky',
#     'luxury',
#     'lymph',
#     'marquis',
#     'matrix',
#     'megahertz',
#     'microwave',
#     'mnemonic',
#     'mystify',
#     'naphtha',
#     'nightclub',
#     'nowadays',
#     'numbskull',
#     'nymph',
#     'onyx',
#     'ovary',
#     'oxidize',
#     'oxygen',
#     'pajama',
#     'peekaboo',
#     'phlegm',
#     'pixel',
#     'pizazz',
#     'pneumonia',
#     'polka',
#     'pshaw',
#     'psyche',
#     'puppy',
#     'puzzling',
#     'quartz',
#     'queue',
#     'quips',
#     'quixotic',
#     'quiz',
#     'quizzes',
#     'quorum',
#     'razzmatazz',
#     'rhubarb',
#     'rhythm',
#     'rickshaw',
#     'schnapps',
#     'scratch',
#     'shiv',
#     'snazzy',
#     'sphinx',
#     'spritz',
#     'squawk',
#     'staff',
#     'strength',
#     'strengths',
#     'stretch',
#     'stronghold',
#     'stymied',
#     'subway',
#     'swivel',
#     'syndrome',
#     'thriftless',
#     'thumbscrew',
#     'topaz',
#     'transcript',
#     'transgress',
#     'transplant',
#     'triphthong',
#     'twelfth',
#     'twelfths',
#     'unknown',
#     'unworthy',
#     'unzip',
#     'uptown',
#     'vaporize',
#     'vixen',
#     'vodka',
#     'voodoo',
#     'vortex',
#     'voyeurism',
#     'walkway',
#     'waltz',
#     'wave',
#     'wavy',
#     'waxy',
#     'wellspring',
#     'wheezy',
#     'whiskey',
#     'whizzing',
#     'whomever',
#     'wimpy',
#     'witchcraft',
#     'wizard',
#     'woozy',
#     'wristwatch',
#     'wyvern',
#     'xylophone',
#     'yachtsman',
#     'yippee',
#     'yoked',
#     'youthful',
#     'yummy',
#     'zephyr',
#     'zigzag',
#     'zigzagging',
#     'zilch',
#     'zipper',
#     'zodiac',
#     'zombie',
# ]

word_list = [
    'abajur',
    'abartı',
    'acaba',
    'acımasız',
    'afilli',
    'akıllı',
    'alaycı',
    'alçakgönüllü',
    'alev',
    'amansız',
    'anbean',
    'angarya',
    'anımsamak',
    'arıza',
    'armağan',
    'artçı',
    'asalak',
    'asfalt',
    'asker',
    'aşama',
    'aşkın',
    'atılgan',
    'avize',
    'ayaküstü',
    'aydınlık',
    'ayrıntı',
    'azim',
    'bakkal',
    'balçık',
    'balina',
    'bambu',
    'barikat',
    'baskın',
    'bavul',
    'beklemek',
    'belirsiz',
    'benekli',
    'berbat',
    'beşer',
    'beyaz',
    'bıkkın',
    'biçim',
    'bilge',
    'bilinçli',
    'bisküvi',
    'bitkisel',
    'bıyık',
    'bluz',
    'boğucu',
    'boyut',
    'bronz',
    'bulut',
    'burun',
    'büyük',
    'canlı',
    'cephe',
    'ceviz',
    'ciddiyet',
    'cinnet',
    'cıvıl',
    'çaba',
    'çalışkan',
    'çarpıcı',
    'çelişkili',
    'çember',
    'çene',
    'çevik',
    'çıkmaz',
    'çiçek',
    'çiftlik',
    'çizgi',
    'çoban',
    'çoklu',
    'çukur',
    'dağınık',
    'damla',
    'darbe',
    'dedikodu',
    'defter',
    'deniz',
    'dertli',
    'dikkat',
    'dilenci',
    'direnç',
    'doğru',
    'durgun',
    'duyarlı',
    'dürüst',
    'ebedi',
    'efsane',
    'ehliyet',
    'eldiven',
    'enerjik',
    'engin',
    'entel',
    'erdem',
    'esir',
    'eşsiz',
    'evren',
    'eğlence',
    'ezgi',
    'fakir',
    'farklı',
    'felaket',
    'ferah',
    'film',
    'fırtına',
    'fiyat',
    'folyo',
    'fonksiyon',
    'fuar',
    'gafil',
    'galaksi',
    'garanti',
    'gazete',
    'gece',
    'gelgit',
    'gerçek',
    'gizem',
    'gökyüzü',
    'gölge',
    'görkem',
    'güleryüz',
    'güven',
    'güzellik',
    'habersiz',
    'hakikat',
    'hayal',
    'huzur',
    'ıssız',
    'içtenlik',
    'ilginç',
    'insan',
    'ipeksi',
    'işlevsel',
    'içgüdü',
    'jilet',
    'kalem',
    'kalp',
    'kardeşlik',
    'karizma',
    'karşılıklı',
    'kasvet',
    'katı',
    'kavramsal',
    'kazanç',
    'kıyamet',
    'klasik',
    'klişe',
    'koku',
    'komik',
    'konfor',
    'konsept',
    'kontrol',
    'korunaklı',
    'kuvvet',
    'kuyruk',
    'kültür',
    'laf',
    'lambası',
    'lezzetli',
    'lider',
    'liman',
    'lütuf',
    'macera',
    'manzara',
    'maruz',
    'masum',
    'mazlum',
    'mehtap',
    'merhamet',
    'mesut',
    'mucize',
    'muhteşem',
    'mutluluk',
    'namus',
    'narin',
    'nazik',
    'nefes',
    'nesne',
    'niyet',
    'objektif',
    'onurlu',
    'oryantal',
    'oyuncu',
    'özgür',
    'öznel',
    'paha',
    'paket',
    'palet',
    'parlak',
    'peyzaj',
    'pilav',
    'piyano',
    'problem',
    'puslu',
    'rahat',
    'rakip',
    'renkli',
    'resim',
    'ritim',
    'roket',
    'rüzgar',
    'sadakat',
    'sakin',
    'samimi',
    'sanat',
    'sarhoş',
    'sağlam',
    'seçim',
    'sevimli',
    'sıcak',
    'sihir',
    'simge',
    'sistem',
    'soğuk',
    'soru',
    'şaheser',
    'şifre',
    'şık',
    'şirin',
    'tatlı',
    'temiz',
    'tesir',
    'tohum',
    'tuhaf',
    'ulaşım',
    'umursamaz',
    'unutkan',
    'uyanık',
    'üzgün',
    'vaat',
    'vakit',
    'varlık',
    'vizyon',
    'yakın',
    'yalnız',
    'yaprak',
    'yasemin',
    'yetenek',
    'yoğun',
    'yüksek',
    'zehir',
    'zeka',
    'zorunlu'
]
